# Generated by Django 2.2 on 2019-04-23 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20190423_0010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        
    ]
