# Generated by Django 2.2 on 2019-04-23 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20190423_2328'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
